[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
solc_version = "0.8.28" # Set default to highest needed version
optimizer_runs = 200

remappings = [
    '@forge-std/=lib/forge-std/',
    '@openzeppelin/=lib/openzeppelin-contracts/',
    '@uniswap/v4-periphery/=lib/v4-periphery/',
    '@uniswap/v4-core/=lib/v4-core/',
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
